before:
  hooks:
    - 'go mod tidy'
    - 'go mod verify'

builds:
  -
    env:
      - 'CGO_ENABLED=0'
      - 'GO111MODULE=on'
      - 'GOPROXY=https://proxy.golang.org,direct'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-a'
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X=github.com/sethvargo/ratchet/internal/version.Name={{ .ProjectName }}'
      - '-X=github.com/sethvargo/ratchet/internal/version.Version={{ .Version }}'
      - '-X=github.com/sethvargo/ratchet/internal/version.Commit={{ .Commit }}'
      - '-extldflags=-static'
    goos:
      - 'darwin'
      - 'linux'
      - 'windows'
    goarch:
      - 'amd64'
      - 'arm64'
    binary: '{{ .ProjectName }}'

dockers:
  -
    use: 'buildx'
    goos: 'linux'
    goarch: 'amd64'
    image_templates:
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}-amd64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:latest-amd64'
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=Ratchet is a tool for improving the security of CI/CD workflows by automating the process of pinning and unpinning upstream versions.'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source=https://github.com/sethvargo/ratchet'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
  -
    use: 'buildx'
    goos: 'linux'
    goarch: 'arm64'
    image_templates:
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}-arm64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:latest-arm64'
    build_flag_templates:
      - '--platform=linux/arm64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=Ratchet is a tool for improving the security of CI/CD workflows by automating the process of pinning and unpinning upstream versions.'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source=https://github.com/sethvargo/ratchet'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'

docker_manifests:
  -
    name_template: 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}'
    image_templates:
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}-amd64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}-arm64'
  -
    name_template: 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64'
  -
    name_template: 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
    image_templates:
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64'
  -
    name_template: 'ghcr.io/sethvargo/{{ .ProjectName }}:latest'
    image_templates:
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:latest-amd64'
      - 'ghcr.io/sethvargo/{{ .ProjectName }}:latest-arm64'

archives:
  - format: 'tar.gz'
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: 'windows'
        format: 'zip'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA512SUMS'
  algorithm: 'sha512'

signs:
  - artifacts: 'checksum'
    args:
      - '--batch'
      - '--local-user'
      - '{{ .Env.GPG_FINGERPRINT }}'
      - '--output'
      - '${signature}'
      - '--detach-sign'
      - '${artifact}'

release:
  draft: false

# changelog:
#   use: 'github-native'
